version: "3.7"
services:
  mongodb:
    container_name: mongodb
    image: mongodb:0.0.1
    build: ./mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongod.log:/etc/mongod.log
      - ./mongodb/data:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file:
      - ./mongodb/.env
    networks:
      - mean
    command:
      - '--auth'
  mariadb:
    container_name: mariadb
    image: mariadb:0.0.1
    build: ./mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
      - ./mariadb/databases:/var/lib/mysql
    env_file:
      - ./mariadb/.env
    networks:
      - mean
  nodejs:
    depends_on:
      - mongodb
      - mariadb
    container_name: nodejs
    image: nodejs:0.0.1
    build: ./nodejs
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/node/app
    env_file:
      - ./app/.env
    networks:
      - mean
    entrypoint: ['bash', './entrypoint.sh']
  nginx:
    depends_on:
      - nodejs
    container_name: nginx
    image: nginx:0.0.1
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    networks:
      - mean
networks:
  mean:
    name: mean
    driver: bridge
